# Generated by Django 4.2.28 on 2026-02-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location_url',
        ),
        migrations.AddField(
            model_name='event',
            name='location_name',
            field=models.CharField(default='لم يحدد', max_length=255),
            preserve_default=False,
        ),
    ]
